package lucidKit.godot;

@:native("godot.EditorPlugin")
extern class EditorPlugin extends Node {
    public function add_autoload_singleton(name: String, path: String): Void;
    public function add_control_to_bottom_panel(control: Control, title: String): ToolButton;
    public function add_control_to_container(container: Int, control: Control): Void;
    public function add_control_to_dock(slot: Int, control: Control): Void;
    public function add_custom_type(type: String, base: String, script: Script, icon: Texture): Void;
    public function add_export_plugin(plugin: EditorExportPlugin): Void;
    public function add_import_plugin(importer: EditorImportPlugin): Void;
    public function add_inspector_plugin(plugin: EditorInspectorPlugin): Void;
    public function add_scene_import_plugin(scene_importer: EditorSceneImporter): Void;
    public function add_spatial_gizmo_plugin(plugin: EditorSpatialGizmoPlugin): Void;
    public function add_tool_menu_item(name: String, handler: Object, callback: String, ud: Variant): Void;
    public function add_tool_submenu_item(name: String, submenu: Object): Void;
    public function apply_changes(): Void;
    public function build(): Bool;
    public function clear(): Void;
    public function disable_plugin(): Void;
    public function edit(object: Object): Void;
    public function enable_plugin(): Void;
    public function forward_canvas_draw_over_viewport(overlay: Control): Void;
    public function forward_canvas_force_draw_over_viewport(overlay: Control): Void;
    public function forward_canvas_gui_input(event: InputEvent): Bool;
    public function forward_spatial_draw_over_viewport(overlay: Control): Void;
    public function forward_spatial_force_draw_over_viewport(overlay: Control): Void;
    public function forward_spatial_gui_input(camera: Camera, event: InputEvent): Bool;
    public function get_breakpoints(): PoolStringArray;
    public function get_editor_interface(): EditorInterface;
    public function get_plugin_icon(): Texture;
    public function get_plugin_name(): String;
    public function get_script_create_dialog(): ScriptCreateDialog;
    public function get_state(): Map<Dynamic, Dynamic>;
    public function get_undo_redo(): UndoRedo;
    public function get_window_layout(layout: ConfigFile): Void;
    public function handles(object: Object): Bool;
    public function has_main_screen(): Bool;
    public function hide_bottom_panel(): Void;
    public function make_bottom_panel_item_visible(item: Control): Void;
    public function make_visible(visible: Bool): Void;
    public function queue_save_layout(): Void;
    public function remove_autoload_singleton(name: String): Void;
    public function remove_control_from_bottom_panel(control: Control): Void;
    public function remove_control_from_container(container: Int, control: Control): Void;
    public function remove_control_from_docks(control: Control): Void;
    public function remove_custom_type(type: String): Void;
    public function remove_export_plugin(plugin: EditorExportPlugin): Void;
    public function remove_import_plugin(importer: EditorImportPlugin): Void;
    public function remove_inspector_plugin(plugin: EditorInspectorPlugin): Void;
    public function remove_scene_import_plugin(scene_importer: EditorSceneImporter): Void;
    public function remove_spatial_gizmo_plugin(plugin: EditorSpatialGizmoPlugin): Void;
    public function remove_tool_menu_item(name: String): Void;
    public function save_external_data(): Void;
    public function set_force_draw_over_forwarding_enabled(): Void;
    public function set_input_event_forwarding_always_enabled(): Void;
    public function set_state(state: Map<Dynamic, Dynamic>): Void;
    public function set_window_layout(layout: ConfigFile): Void;
    public function update_overlays(): Int;
    @:native("__new")
    public function new();
}
