package lucidKit.godot;

@:native("godot.Generic6DOFJoint")
extern class Generic6DOFJoint extends Joint {
    public var angular_limit_x__damping: Float;
    public var angular_limit_x__enabled: Bool;
    public var angular_limit_x__erp: Float;
    public var angular_limit_x__force_limit: Float;
    public var angular_limit_x__lower_angle: Float;
    public var angular_limit_x__restitution: Float;
    public var angular_limit_x__softness: Float;
    public var angular_limit_x__upper_angle: Float;
    public var angular_limit_y__damping: Float;
    public var angular_limit_y__enabled: Bool;
    public var angular_limit_y__erp: Float;
    public var angular_limit_y__force_limit: Float;
    public var angular_limit_y__lower_angle: Float;
    public var angular_limit_y__restitution: Float;
    public var angular_limit_y__softness: Float;
    public var angular_limit_y__upper_angle: Float;
    public var angular_limit_z__damping: Float;
    public var angular_limit_z__enabled: Bool;
    public var angular_limit_z__erp: Float;
    public var angular_limit_z__force_limit: Float;
    public var angular_limit_z__lower_angle: Float;
    public var angular_limit_z__restitution: Float;
    public var angular_limit_z__softness: Float;
    public var angular_limit_z__upper_angle: Float;
    public var angular_motor_x__enabled: Bool;
    public var angular_motor_x__force_limit: Float;
    public var angular_motor_x__target_velocity: Float;
    public var angular_motor_y__enabled: Bool;
    public var angular_motor_y__force_limit: Float;
    public var angular_motor_y__target_velocity: Float;
    public var angular_motor_z__enabled: Bool;
    public var angular_motor_z__force_limit: Float;
    public var angular_motor_z__target_velocity: Float;
    public var angular_spring_x__damping: Float;
    public var angular_spring_x__enabled: Bool;
    public var angular_spring_x__equilibrium_point: Float;
    public var angular_spring_x__stiffness: Float;
    public var angular_spring_y__damping: Float;
    public var angular_spring_y__enabled: Bool;
    public var angular_spring_y__equilibrium_point: Float;
    public var angular_spring_y__stiffness: Float;
    public var angular_spring_z__damping: Float;
    public var angular_spring_z__enabled: Bool;
    public var angular_spring_z__equilibrium_point: Float;
    public var angular_spring_z__stiffness: Float;
    public var linear_limit_x__damping: Float;
    public var linear_limit_x__enabled: Bool;
    public var linear_limit_x__lower_distance: Float;
    public var linear_limit_x__restitution: Float;
    public var linear_limit_x__softness: Float;
    public var linear_limit_x__upper_distance: Float;
    public var linear_limit_y__damping: Float;
    public var linear_limit_y__enabled: Bool;
    public var linear_limit_y__lower_distance: Float;
    public var linear_limit_y__restitution: Float;
    public var linear_limit_y__softness: Float;
    public var linear_limit_y__upper_distance: Float;
    public var linear_limit_z__damping: Float;
    public var linear_limit_z__enabled: Bool;
    public var linear_limit_z__lower_distance: Float;
    public var linear_limit_z__restitution: Float;
    public var linear_limit_z__softness: Float;
    public var linear_limit_z__upper_distance: Float;
    public var linear_motor_x__enabled: Bool;
    public var linear_motor_x__force_limit: Float;
    public var linear_motor_x__target_velocity: Float;
    public var linear_motor_y__enabled: Bool;
    public var linear_motor_y__force_limit: Float;
    public var linear_motor_y__target_velocity: Float;
    public var linear_motor_z__enabled: Bool;
    public var linear_motor_z__force_limit: Float;
    public var linear_motor_z__target_velocity: Float;
    public var linear_spring_x__damping: Float;
    public var linear_spring_x__enabled: Bool;
    public var linear_spring_x__equilibrium_point: Float;
    public var linear_spring_x__stiffness: Float;
    public var linear_spring_y__damping: Float;
    public var linear_spring_y__enabled: Bool;
    public var linear_spring_y__equilibrium_point: Float;
    public var linear_spring_y__stiffness: Float;
    public var linear_spring_z__damping: Float;
    public var linear_spring_z__enabled: Bool;
    public var linear_spring_z__equilibrium_point: Float;
    public var linear_spring_z__stiffness: Float;
    public function get_flag_x(flag: Int): Bool;
    public function get_flag_y(flag: Int): Bool;
    public function get_flag_z(flag: Int): Bool;
    public function get_param_x(param: Int): Float;
    public function get_param_y(param: Int): Float;
    public function get_param_z(param: Int): Float;
    public function set_flag_x(flag: Int, value: Bool): Void;
    public function set_flag_y(flag: Int, value: Bool): Void;
    public function set_flag_z(flag: Int, value: Bool): Void;
    public function set_param_x(param: Int, value: Float): Void;
    public function set_param_y(param: Int, value: Float): Void;
    public function set_param_z(param: Int, value: Float): Void;
    @:native("__new")
    public function new();
}
