package lucidKit.godot;

@:native("godot.ParticlesMaterial")
extern class ParticlesMaterial extends Material {
    public var angle: Float;
    public var angle_curve: Texture;
    public var angle_random: Float;
    public var angular_velocity: Float;
    public var angular_velocity_curve: Texture;
    public var angular_velocity_random: Float;
    public var anim_offset: Float;
    public var anim_offset_curve: Texture;
    public var anim_offset_random: Float;
    public var anim_speed: Float;
    public var anim_speed_curve: Texture;
    public var anim_speed_random: Float;
    public var color: Color;
    public var color_initial_ramp: Texture;
    public var color_ramp: Texture;
    public var damping: Float;
    public var damping_curve: Texture;
    public var damping_random: Float;
    public var direction: Vector3;
    public var emission_box_extents: Vector3;
    public var emission_color_texture: Texture;
    public var emission_normal_texture: Texture;
    public var emission_point_count: Int;
    public var emission_point_texture: Texture;
    public var emission_ring_axis: Vector3;
    public var emission_ring_height: Float;
    public var emission_ring_inner_radius: Float;
    public var emission_ring_radius: Float;
    public var emission_shape: Int;
    public var emission_sphere_radius: Float;
    public var flag_align_y: Bool;
    public var flag_disable_z: Bool;
    public var flag_rotate_y: Bool;
    public var flatness: Float;
    public var gravity: Vector3;
    public var hue_variation: Float;
    public var hue_variation_curve: Texture;
    public var hue_variation_random: Float;
    public var initial_velocity: Float;
    public var initial_velocity_random: Float;
    public var lifetime_randomness: Float;
    public var linear_accel: Float;
    public var linear_accel_curve: Texture;
    public var linear_accel_random: Float;
    public var orbit_velocity: Float;
    public var orbit_velocity_curve: Texture;
    public var orbit_velocity_random: Float;
    public var radial_accel: Float;
    public var radial_accel_curve: Texture;
    public var radial_accel_random: Float;
    public var scale: Float;
    public var scale_curve: Texture;
    public var scale_random: Float;
    public var spread: Float;
    public var tangential_accel: Float;
    public var tangential_accel_curve: Texture;
    public var tangential_accel_random: Float;
    public var trail_color_modifier: GradientTexture;
    public var trail_divisor: Int;
    public var trail_size_modifier: CurveTexture;
    public function get_flag(flag: Int): Bool;
    public function get_param(param: Int): Float;
    public function get_param_randomness(param: Int): Float;
    public function get_param_texture(param: Int): Texture;
    public function set_flag(flag: Int, enable: Bool): Void;
    public function set_param(param: Int, value: Float): Void;
    public function set_param_randomness(param: Int, randomness: Float): Void;
    public function set_param_texture(param: Int, texture: Texture): Void;
    @:native("__new")
    public function new();
}
