package lucidKit.godot;

@:native("godot.Physics2DServer")
extern class Physics2DServer extends Object {
    public function area_add_shape(area: RID, shape: RID, transform: Transform2D, disabled: Bool): Void;
    public function area_attach_canvas_instance_id(area: RID, id: Int): Void;
    public function area_attach_object_instance_id(area: RID, id: Int): Void;
    public function area_clear_shapes(area: RID): Void;
    public function area_create(): RID;
    public function area_get_canvas_instance_id(area: RID): Int;
    public function area_get_object_instance_id(area: RID): Int;
    public function area_get_param(area: RID, param: Int): Variant;
    public function area_get_shape(area: RID, shape_idx: Int): RID;
    public function area_get_shape_count(area: RID): Int;
    public function area_get_shape_transform(area: RID, shape_idx: Int): Transform2D;
    public function area_get_space(area: RID): RID;
    public function area_get_space_override_mode(area: RID): Int;
    public function area_get_transform(area: RID): Transform2D;
    public function area_remove_shape(area: RID, shape_idx: Int): Void;
    public function area_set_area_monitor_callback(area: RID, receiver: Object, method: String): Void;
    public function area_set_collision_layer(area: RID, layer: Int): Void;
    public function area_set_collision_mask(area: RID, mask: Int): Void;
    public function area_set_monitor_callback(area: RID, receiver: Object, method: String): Void;
    public function area_set_monitorable(area: RID, monitorable: Bool): Void;
    public function area_set_param(area: RID, param: Int, value: Variant): Void;
    public function area_set_shape(area: RID, shape_idx: Int, shape: RID): Void;
    public function area_set_shape_disabled(area: RID, shape_idx: Int, disabled: Bool): Void;
    public function area_set_shape_transform(area: RID, shape_idx: Int, transform: Transform2D): Void;
    public function area_set_space(area: RID, space: RID): Void;
    public function area_set_space_override_mode(area: RID, mode: Int): Void;
    public function area_set_transform(area: RID, transform: Transform2D): Void;
    public function body_add_central_force(body: RID, force: GdVector2): Void;
    public function body_add_collision_exception(body: RID, excepted_body: RID): Void;
    public function body_add_force(body: RID, offset: GdVector2, force: GdVector2): Void;
    public function body_add_shape(body: RID, shape: RID, transform: Transform2D, disabled: Bool): Void;
    public function body_add_torque(body: RID, torque: Float): Void;
    public function body_apply_central_impulse(body: RID, impulse: GdVector2): Void;
    public function body_apply_impulse(body: RID, position: GdVector2, impulse: GdVector2): Void;
    public function body_apply_torque_impulse(body: RID, impulse: Float): Void;
    public function body_attach_canvas_instance_id(body: RID, id: Int): Void;
    public function body_attach_object_instance_id(body: RID, id: Int): Void;
    public function body_clear_shapes(body: RID): Void;
    public function body_create(): RID;
    public function body_get_canvas_instance_id(body: RID): Int;
    public function body_get_collision_layer(body: RID): Int;
    public function body_get_collision_mask(body: RID): Int;
    public function body_get_continuous_collision_detection_mode(body: RID): Int;
    public function body_get_direct_state(body: RID): Physics2DDirectBodyState;
    public function body_get_max_contacts_reported(body: RID): Int;
    public function body_get_mode(body: RID): Int;
    public function body_get_object_instance_id(body: RID): Int;
    public function body_get_param(body: RID, param: Int): Float;
    public function body_get_shape(body: RID, shape_idx: Int): RID;
    public function body_get_shape_count(body: RID): Int;
    public function body_get_shape_metadata(body: RID, shape_idx: Int): Variant;
    public function body_get_shape_transform(body: RID, shape_idx: Int): Transform2D;
    public function body_get_space(body: RID): RID;
    public function body_get_state(body: RID, state: Int): Variant;
    public function body_is_omitting_force_integration(body: RID): Bool;
    public function body_remove_collision_exception(body: RID, excepted_body: RID): Void;
    public function body_remove_shape(body: RID, shape_idx: Int): Void;
    public function body_set_axis_velocity(body: RID, axis_velocity: GdVector2): Void;
    public function body_set_collision_layer(body: RID, layer: Int): Void;
    public function body_set_collision_mask(body: RID, mask: Int): Void;
    public function body_set_continuous_collision_detection_mode(body: RID, mode: Int): Void;
    public function body_set_force_integration_callback(body: RID, receiver: Object, method: String, userdata: Variant): Void;
    public function body_set_max_contacts_reported(body: RID, amount: Int): Void;
    public function body_set_mode(body: RID, mode: Int): Void;
    public function body_set_omit_force_integration(body: RID, enable: Bool): Void;
    public function body_set_param(body: RID, param: Int, value: Float): Void;
    public function body_set_shape(body: RID, shape_idx: Int, shape: RID): Void;
    public function body_set_shape_as_one_way_collision(body: RID, shape_idx: Int, enable: Bool, margin: Float): Void;
    public function body_set_shape_disabled(body: RID, shape_idx: Int, disabled: Bool): Void;
    public function body_set_shape_metadata(body: RID, shape_idx: Int, metadata: Variant): Void;
    public function body_set_shape_transform(body: RID, shape_idx: Int, transform: Transform2D): Void;
    public function body_set_space(body: RID, space: RID): Void;
    public function body_set_state(body: RID, state: Int, value: Variant): Void;
    public function body_test_motion(body: RID, from: Transform2D, motion: GdVector2, infinite_inertia: Bool, margin: Float, result: Physics2DTestMotionResult, exclude_raycast_shapes: Bool, exclude: Array<Dynamic>): Bool;
    public function capsule_shape_create(): RID;
    public function circle_shape_create(): RID;
    public function concave_polygon_shape_create(): RID;
    public function convex_polygon_shape_create(): RID;
    public function damped_spring_joint_create(anchor_a: GdVector2, anchor_b: GdVector2, body_a: RID, body_b: RID): RID;
    public function damped_string_joint_get_param(joint: RID, param: Int): Float;
    public function damped_string_joint_set_param(joint: RID, param: Int, value: Float): Void;
    public function free_rid(rid: RID): Void;
    public function get_process_info(process_info: Int): Int;
    public function groove_joint_create(groove1_a: GdVector2, groove2_a: GdVector2, anchor_b: GdVector2, body_a: RID, body_b: RID): RID;
    public function joint_get_param(joint: RID, param: Int): Float;
    public function joint_get_type(joint: RID): Int;
    public function joint_set_param(joint: RID, param: Int, value: Float): Void;
    public function line_shape_create(): RID;
    public function pin_joint_create(anchor: GdVector2, body_a: RID, body_b: RID): RID;
    public function ray_shape_create(): RID;
    public function rectangle_shape_create(): RID;
    public function segment_shape_create(): RID;
    public function set_active(active: Bool): Void;
    public function set_collision_iterations(iterations: Int): Void;
    public function shape_get_data(shape: RID): Variant;
    public function shape_get_type(shape: RID): Int;
    public function shape_set_data(shape: RID, data: Variant): Void;
    public function space_create(): RID;
    public function space_get_direct_state(space: RID): Physics2DDirectSpaceState;
    public function space_get_param(space: RID, param: Int): Float;
    public function space_is_active(space: RID): Bool;
    public function space_set_active(space: RID, active: Bool): Void;
    public function space_set_param(space: RID, param: Int, value: Float): Void;
    @:native("__new")
    public function new();
}
