package lucidKit.godot;

@:native("godot.Viewport")
extern class Viewport extends Node {
    public var arvr: Bool;
    public var audio_listener_enable_2d: Bool;
    public var audio_listener_enable_3d: Bool;
    public var canvas_transform: Transform2D;
    public var debanding: Bool;
    public var debug_draw: Int;
    public var disable_3d: Bool;
    public var fxaa: Bool;
    public var global_canvas_transform: Transform2D;
    public var gui_disable_input: Bool;
    public var gui_snap_controls_to_pixels: Bool;
    public var handle_input_locally: Bool;
    public var hdr: Bool;
    public var keep_3d_linear: Bool;
    public var msaa: Int;
    public var own_world: Bool;
    public var physics_interpolation_mode: Int;
    public var physics_object_picking: Bool;
    public var render_direct_to_screen: Bool;
    public var render_target_clear_mode: Int;
    public var render_target_update_mode: Int;
    public var render_target_v_flip: Bool;
    public var shadow_atlas_quad_0: Int;
    public var shadow_atlas_quad_1: Int;
    public var shadow_atlas_quad_2: Int;
    public var shadow_atlas_quad_3: Int;
    public var shadow_atlas_size: Int;
    public var sharpen_intensity: Float;
    public var size: Vector2;
    public var size_override_stretch: Bool;
    public var transparent_bg: Bool;
    public var usage: Int;
    public var use_32_bpc_depth: Bool;
    public var world: World;
    public var world_2d: World2D;
    public function find_world(): World;
    public function find_world_2d(): World2D;
    public function get_camera(): Camera;
    public function get_final_transform(): Transform2D;
    public function get_modal_stack_top(): Control;
    public function get_mouse_position(): Vector2;
    public function get_render_info(info: Int): Int;
    public function get_shadow_atlas_quadrant_subdiv(quadrant: Int): Int;
    public function get_size_override(): Vector2;
    public function get_texture(): ViewportTexture;
    public function get_viewport_rid(): RID;
    public function get_visible_rect(): Rect2;
    public function gui_get_drag_data(): Variant;
    public function gui_has_modal_stack(): Bool;
    public function gui_is_drag_successful(): Bool;
    public function gui_is_dragging(): Bool;
    public function input(local_event: InputEvent): Void;
    public function is_input_handled(): Bool;
    public function is_size_override_enabled(): Bool;
    public function set_attach_to_screen_rect(rect: Rect2): Void;
    public function set_input_as_handled(): Void;
    public function set_shadow_atlas_quadrant_subdiv(quadrant: Int, subdiv: Int): Void;
    public function set_size_override(enable: Bool, size: GdVector2, margin: GdVector2): Void;
    public function unhandled_input(local_event: InputEvent): Void;
    public function update_worlds(): Void;
    public function warp_mouse(to_position: GdVector2): Void;
    @:native("__new")
    public function new();
}
