-- Generated by Haxe 4.3.6
local _hx_hidden = {__id__=true, hx__closures=true, super=true, prototype=true, __fields__=true, __ifields__=true, __class__=true, __properties__=true, __fields__=true, __name__=true}

_hx_array_mt = {
    __newindex = function(t,k,v)
        local len = t.length
        t.length =  k >= len and (k + 1) or len
        rawset(t,k,v)
    end
}

function _hx_is_array(o)
    return type(o) == "table"
        and o.__enum__ == nil
        and getmetatable(o) == _hx_array_mt
end



function _hx_tab_array(tab, length)
    tab.length = length
    return setmetatable(tab, _hx_array_mt)
end



function _hx_print_class(obj, depth)
    local first = true
    local result = ''
    for k,v in pairs(obj) do
        if _hx_hidden[k] == nil then
            if first then
                first = false
            else
                result = result .. ', '
            end
            if _hx_hidden[k] == nil then
                result = result .. k .. ':' .. _hx_tostring(v, depth+1)
            end
        end
    end
    return '{ ' .. result .. ' }'
end

function _hx_print_enum(o, depth)
    if o.length == 2 then
        return o[0]
    else
        local str = o[0] .. "("
        for i = 2, (o.length-1) do
            if i ~= 2 then
                str = str .. "," .. _hx_tostring(o[i], depth+1)
            else
                str = str .. _hx_tostring(o[i], depth+1)
            end
        end
        return str .. ")"
    end
end

function _hx_tostring(obj, depth)
    if depth == nil then
        depth = 0
    elseif depth > 5 then
        return "<...>"
    end

    local tstr = _G.type(obj)
    if tstr == "string" then return obj
    elseif tstr == "nil" then return "null"
    elseif tstr == "number" then
        if obj == _G.math.POSITIVE_INFINITY then return "Infinity"
        elseif obj == _G.math.NEGATIVE_INFINITY then return "-Infinity"
        elseif obj == 0 then return "0"
        elseif obj ~= obj then return "NaN"
        else return _G.tostring(obj)
        end
    elseif tstr == "boolean" then return _G.tostring(obj)
    elseif tstr == "userdata" then
        local mt = _G.getmetatable(obj)
        if mt ~= nil and mt.__tostring ~= nil then
            return _G.tostring(obj)
        else
            return "<userdata>"
        end
    elseif tstr == "function" then return "<function>"
    elseif tstr == "thread" then return "<thread>"
    elseif tstr == "table" then
        if obj.__enum__ ~= nil then
            return _hx_print_enum(obj, depth)
        elseif obj.toString ~= nil and not _hx_is_array(obj) then return obj:toString()
        elseif _hx_is_array(obj) then
            if obj.length > 5 then
                return "[...]"
            else
                local str = ""
                for i=0, (obj.length-1) do
                    if i == 0 then
                        str = str .. _hx_tostring(obj[i], depth+1)
                    else
                        str = str .. "," .. _hx_tostring(obj[i], depth+1)
                    end
                end
                return "[" .. str .. "]"
            end
        elseif obj.__class__ ~= nil then
            return _hx_print_class(obj, depth)
        else
            local buffer = {}
            local ref = obj
            if obj.__fields__ ~= nil then
                ref = obj.__fields__
            end
            for k,v in pairs(ref) do
                if _hx_hidden[k] == nil then
                    _G.table.insert(buffer, _hx_tostring(k, depth+1) .. ' : ' .. _hx_tostring(obj[k], depth+1))
                end
            end

            return "{ " .. table.concat(buffer, ", ") .. " }"
        end
    else
        _G.error("Unknown Lua type", 0)
        return ""
    end
end

local function _hx_obj_newindex(t,k,v)
    t.__fields__[k] = true
    rawset(t,k,v)
end

local _hx_obj_mt = {__newindex=_hx_obj_newindex, __tostring=_hx_tostring}

local function _hx_a(...)
  local __fields__ = {};
  local ret = {__fields__ = __fields__};
  local max = select('#',...);
  local tab = {...};
  local cur = 1;
  while cur < max do
    local v = tab[cur];
    __fields__[v] = true;
    ret[v] = tab[cur+1];
    cur = cur + 2
  end
  return setmetatable(ret, _hx_obj_mt)
end

local function _hx_e()
  return setmetatable({__fields__ = {}}, _hx_obj_mt)
end

local function _hx_o(obj)
  return setmetatable(obj, _hx_obj_mt)
end

local function _hx_new(prototype)
  return setmetatable({__fields__ = {}}, {__newindex=_hx_obj_newindex, __index=prototype, __tostring=_hx_tostring})
end

function _hx_field_arr(obj)
    local res = {}
    local idx = 0
    if obj.__fields__ ~= nil then
        obj = obj.__fields__
    end
    for k,v in pairs(obj) do
        if _hx_hidden[k] == nil then
            res[idx] = k
            idx = idx + 1
        end
    end
    return _hx_tab_array(res, idx)
end

local _hxClasses = {}
local Int = _hx_e();
local Dynamic = _hx_e();
local Float = _hx_e();
local Bool = _hx_e();
local Class = _hx_e();
local Enum = _hx_e();

local Array = _hx_e()
local MonoObject = _hx_e()
local HelloHelper = _hx_e()
local Main = _hx_e()
local Math = _hx_e()
local Person = _hx_e()
local String = _hx_e()
local Std = _hx_e()
__haxe_Exception = _hx_e()
__haxe_Log = _hx_e()
__haxe_NativeStackTrace = _hx_e()
__haxe_ValueException = _hx_e()
__haxe_exceptions_PosException = _hx_e()
__haxe_exceptions_NotImplementedException = _hx_e()
__haxe_iterators_ArrayIterator = _hx_e()
__haxe_iterators_ArrayKeyValueIterator = _hx_e()
__koneko_core_InstanceObject = _hx_e()
__koneko_godot_Vector2Axis = _hx_e()
__koneko_godot_Vector2 = _hx_e()
__koneko_godot_Vector3Axis = _hx_e()
__koneko_godot_Vector3 = _hx_e()
__lua_Boot = _hx_e()
__lua_UserData = _hx_e()
__lua_Thread = _hx_e()

local _hx_bind, _hx_bit, _hx_staticToInstance, _hx_funcToField, _hx_maxn, _hx_print, _hx_apply_self, _hx_box_mr, _hx_bit_clamp, _hx_table, _hx_bit_raw
local _hx_pcall_default = {};
local _hx_pcall_break = {};

Array.new = function() 
  local self = _hx_new(Array.prototype)
  Array.super(self)
  return self
end
Array.super = function(self) 
  _hx_tab_array(self, 0);
end
Array.__name__ = true
Array.prototype = _hx_e();
Array.prototype.concat = function(self,a) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  local _g2 = self;
  while (_g1 < _g2.length) do _hx_do_first_1 = false;
    
    local i = _g2[_g1];
    _g1 = _g1 + 1;
    _g:push(i);
  end;
  local ret = _g;
  local _g = 0;
  while (_g < a.length) do _hx_do_first_1 = false;
    
    local i = a[_g];
    _g = _g + 1;
    ret:push(i);
  end;
  do return ret end
end
Array.prototype.join = function(self,sep) 
  local tbl = ({});
  local _g_current = 0;
  local _g_array = self;
  while (_g_current < _g_array.length) do _hx_do_first_1 = false;
    
    _g_current = _g_current + 1;
    local i = _g_array[_g_current - 1];
    _G.table.insert(tbl, Std.string(i));
  end;
  do return _G.table.concat(tbl, sep) end
end
Array.prototype.pop = function(self) 
  if (self.length == 0) then 
    do return nil end;
  end;
  local ret = self[self.length - 1];
  self[self.length - 1] = nil;
  self.length = self.length - 1;
  do return ret end
end
Array.prototype.push = function(self,x) 
  self[self.length] = x;
  do return self.length end
end
Array.prototype.reverse = function(self) 
  local tmp;
  local i = 0;
  while (i < Std.int(self.length / 2)) do _hx_do_first_1 = false;
    
    tmp = self[i];
    self[i] = self[(self.length - i) - 1];
    self[(self.length - i) - 1] = tmp;
    i = i + 1;
  end;
end
Array.prototype.shift = function(self) 
  if (self.length == 0) then 
    do return nil end;
  end;
  local ret = self[0];
  if (self.length == 1) then 
    self[0] = nil;
  else
    if (self.length > 1) then 
      self[0] = self[1];
      _G.table.remove(self, 1);
    end;
  end;
  local tmp = self;
  tmp.length = tmp.length - 1;
  do return ret end
end
Array.prototype.slice = function(self,pos,_end) 
  if ((_end == nil) or (_end > self.length)) then 
    _end = self.length;
  else
    if (_end < 0) then 
      _end = _G.math.fmod((self.length - (_G.math.fmod(-_end, self.length))), self.length);
    end;
  end;
  if (pos < 0) then 
    pos = _G.math.fmod((self.length - (_G.math.fmod(-pos, self.length))), self.length);
  end;
  if ((pos > _end) or (pos > self.length)) then 
    do return _hx_tab_array({}, 0) end;
  end;
  local ret = _hx_tab_array({}, 0);
  local _g = pos;
  local _g1 = _end;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    ret:push(self[i]);
  end;
  do return ret end
end
Array.prototype.sort = function(self,f) 
  local i = 0;
  local l = self.length;
  while (i < l) do _hx_do_first_1 = false;
    
    local swap = false;
    local j = 0;
    local max = (l - i) - 1;
    while (j < max) do _hx_do_first_2 = false;
      
      if (f(self[j], self[j + 1]) > 0) then 
        local tmp = self[j + 1];
        self[j + 1] = self[j];
        self[j] = tmp;
        swap = true;
      end;
      j = j + 1;
    end;
    if (not swap) then 
      break;
    end;
    i = i + 1;
  end;
end
Array.prototype.splice = function(self,pos,len) 
  if ((len < 0) or (pos > self.length)) then 
    do return _hx_tab_array({}, 0) end;
  else
    if (pos < 0) then 
      pos = self.length - (_G.math.fmod(-pos, self.length));
    end;
  end;
  len = Math.min(len, self.length - pos);
  local ret = _hx_tab_array({}, 0);
  local _g = pos;
  local _g1 = pos + len;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    ret:push(self[i]);
    self[i] = self[i + len];
  end;
  local _g = pos + len;
  local _g1 = self.length;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    self[i] = self[i + len];
  end;
  local tmp = self;
  tmp.length = tmp.length - len;
  do return ret end
end
Array.prototype.toString = function(self) 
  local tbl = ({});
  _G.table.insert(tbl, "[");
  _G.table.insert(tbl, self:join(","));
  _G.table.insert(tbl, "]");
  do return _G.table.concat(tbl, "") end
end
Array.prototype.unshift = function(self,x) 
  local len = self.length;
  local _g = 0;
  local _g1 = len;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    self[len - i] = self[(len - i) - 1];
  end;
  self[0] = x;
end
Array.prototype.insert = function(self,pos,x) 
  if (pos > self.length) then 
    pos = self.length;
  end;
  if (pos < 0) then 
    pos = self.length + pos;
    if (pos < 0) then 
      pos = 0;
    end;
  end;
  local cur_len = self.length;
  while (cur_len > pos) do _hx_do_first_1 = false;
    
    self[cur_len] = self[cur_len - 1];
    cur_len = cur_len - 1;
  end;
  self[pos] = x;
end
Array.prototype.remove = function(self,x) 
  local _g = 0;
  local _g1 = self.length;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    if (self[i] == x) then 
      local _g = i;
      local _g1 = self.length - 1;
      while (_g < _g1) do _hx_do_first_2 = false;
        
        _g = _g + 1;
        local j = _g - 1;
        self[j] = self[j + 1];
      end;
      self[self.length - 1] = nil;
      self.length = self.length - 1;
      do return true end;
    end;
  end;
  do return false end
end
Array.prototype.contains = function(self,x) 
  local _g = 0;
  local _g1 = self.length;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    if (self[i] == x) then 
      do return true end;
    end;
  end;
  do return false end
end
Array.prototype.indexOf = function(self,x,fromIndex) 
  local _end = self.length;
  if (fromIndex == nil) then 
    fromIndex = 0;
  else
    if (fromIndex < 0) then 
      fromIndex = self.length + fromIndex;
      if (fromIndex < 0) then 
        fromIndex = 0;
      end;
    end;
  end;
  local _g = fromIndex;
  local _g1 = _end;
  while (_g < _g1) do _hx_do_first_1 = false;
    
    _g = _g + 1;
    local i = _g - 1;
    if (x == self[i]) then 
      do return i end;
    end;
  end;
  do return -1 end
end
Array.prototype.lastIndexOf = function(self,x,fromIndex) 
  if ((fromIndex == nil) or (fromIndex >= self.length)) then 
    fromIndex = self.length - 1;
  else
    if (fromIndex < 0) then 
      fromIndex = self.length + fromIndex;
      if (fromIndex < 0) then 
        do return -1 end;
      end;
    end;
  end;
  local i = fromIndex;
  while (i >= 0) do _hx_do_first_1 = false;
    
    if (self[i] == x) then 
      do return i end;
    else
      i = i - 1;
    end;
  end;
  do return -1 end
end
Array.prototype.copy = function(self) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  local _g2 = self;
  while (_g1 < _g2.length) do _hx_do_first_1 = false;
    
    local i = _g2[_g1];
    _g1 = _g1 + 1;
    _g:push(i);
  end;
  do return _g end
end
Array.prototype.map = function(self,f) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  local _g2 = self;
  while (_g1 < _g2.length) do _hx_do_first_1 = false;
    
    local i = _g2[_g1];
    _g1 = _g1 + 1;
    _g:push(f(i));
  end;
  do return _g end
end
Array.prototype.filter = function(self,f) 
  local _g = _hx_tab_array({}, 0);
  local _g1 = 0;
  local _g2 = self;
  while (_g1 < _g2.length) do _hx_do_first_1 = false;
    
    local i = _g2[_g1];
    _g1 = _g1 + 1;
    if (f(i)) then 
      _g:push(i);
    end;
  end;
  do return _g end
end
Array.prototype.iterator = function(self) 
  do return __haxe_iterators_ArrayIterator.new(self) end
end
Array.prototype.keyValueIterator = function(self) 
  do return __haxe_iterators_ArrayKeyValueIterator.new(self) end
end
Array.prototype.resize = function(self,len) 
  if (self.length < len) then 
    self.length = len;
  else
    if (self.length > len) then 
      local _g = len;
      local _g1 = self.length;
      while (_g < _g1) do _hx_do_first_1 = false;
        
        _g = _g + 1;
        local i = _g - 1;
        self[i] = nil;
      end;
      self.length = len;
    end;
  end;
end

Array.prototype.__class__ =  Array

MonoObject.new = {}
MonoObject.__name__ = true
MonoObject.prototype = _hx_e();

MonoObject.prototype.__class__ =  MonoObject

HelloHelper.new = function() 
  local self = _hx_new(HelloHelper.prototype)
  HelloHelper.super(self)
  return self
end
HelloHelper.super = function(self) 
  self.instance = _HelloHelper.__new();
end
HelloHelper.__name__ = true
HelloHelper.prototype = _hx_e();
HelloHelper.prototype.sayHello = function(self,name) 
  self.instance:sayHello(name);
end

HelloHelper.prototype.__class__ =  HelloHelper
HelloHelper.__super__ = MonoObject
setmetatable(HelloHelper.prototype,{__index=MonoObject.prototype})

Main.new = {}
Main.__name__ = true
Main.main = function() 
  __haxe_Log.trace("Hello, World!", _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Main.hx",lineNumber=11,className="Main",methodName="main"}));
  __haxe_Log.trace(Main.add(4, 6), _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Main.hx",lineNumber=12,className="Main",methodName="main"}));
  __haxe_Log.trace(100, _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true,customParams=true},fileName="src/Main.hx",lineNumber=13,className="Main",methodName="main",customParams=_hx_tab_array({[0]=28}, 1)}));
  Main.sayHello("mintkat");
  Main.sayHello("Lucas C. Abbas");
  Main.sayHello("Lily");
  local lucas = Person.new("Lucas", 20, "2004-10-04");
  __haxe_Log.trace(lucas:toString(), _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Main.hx",lineNumber=19,className="Main",methodName="main"}));
  lucas:sayHello();
  local helper = HelloHelper.new();
  helper:sayHello("mintkat");
  local vec3 = __koneko_godot_Vector3.new(3, 2, 3);
  __haxe_Log.trace(vec3:toString(), _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Main.hx",lineNumber=29,className="Main",methodName="main"}));
  local vec2 = __koneko_godot_Vector2.new(6, 1);
  __haxe_Log.trace(vec2:toString(), _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Main.hx",lineNumber=32,className="Main",methodName="main"}));
end
Main.add = function(a,b) 
  do return a + b end;
end
Main.sayHello = function(name) 
  __haxe_Log.trace(Std.string(Std.string("Hello, ") .. Std.string(name)) .. Std.string("!"), _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Main.hx",lineNumber=40,className="Main",methodName="sayHello"}));
end

Math.new = {}
Math.__name__ = true
Math.isNaN = function(f) 
  do return f ~= f end;
end
Math.isFinite = function(f) 
  if (f > -_G.math.huge) then 
    do return f < _G.math.huge end;
  else
    do return false end;
  end;
end
Math.min = function(a,b) 
  if (Math.isNaN(a) or Math.isNaN(b)) then 
    do return (0/0) end;
  else
    do return _G.math.min(a, b) end;
  end;
end

Person.new = function(name,age,birthday) 
  local self = _hx_new(Person.prototype)
  Person.super(self,name,age,birthday)
  return self
end
Person.super = function(self,name,age,birthday) 
  self.name = name;
  self.age = age;
  self.birthday = birthday;
end
Person.__name__ = true
Person.prototype = _hx_e();
Person.prototype.sayHello = function(self) 
  __haxe_Log.trace(Std.string(Std.string("Hello, ") .. Std.string(self.name)) .. Std.string("!"), _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="src/Person.hx",lineNumber=15,className="Person",methodName="sayHello"}));
end
Person.prototype.getAge = function(self) 
  do return self.age end
end
Person.prototype.setAge = function(self,age) 
  self.age = age;
end
Person.prototype.getBirthday = function(self) 
  do return self.birthday end
end
Person.prototype.setBirthday = function(self,birthday) 
  self.birthday = birthday;
end
Person.prototype.toString = function(self) 
  do return Std.string(Std.string(Std.string(Std.string(Std.string(Std.string("Person { name = ") .. Std.string(self.name)) .. Std.string(", age = ")) .. Std.string(self.age)) .. Std.string(", birthday = ")) .. Std.string(self.birthday)) .. Std.string(" } ") end
end

Person.prototype.__class__ =  Person

String.new = function(string) 
  local self = _hx_new(String.prototype)
  String.super(self,string)
  self = string
  return self
end
String.super = function(self,string) 
end
String.__name__ = true
String.__index = function(s,k) 
  if (k == "length") then 
    do return _G.string.len(s) end;
  else
    local o = String.prototype;
    local field = k;
    if ((function() 
      local _hx_1
      if ((_G.type(o) == "function") and not ((function() 
        local _hx_2
        if (_G.type(o) ~= "table") then 
        _hx_2 = false; else 
        _hx_2 = o.__name__; end
        return _hx_2
      end )() or (function() 
        local _hx_3
        if (_G.type(o) ~= "table") then 
        _hx_3 = false; else 
        _hx_3 = o.__ename__; end
        return _hx_3
      end )())) then 
      _hx_1 = false; elseif ((_G.type(o) == "string") and ((String.prototype[field] ~= nil) or (field == "length"))) then 
      _hx_1 = true; elseif (o.__fields__ ~= nil) then 
      _hx_1 = o.__fields__[field] ~= nil; else 
      _hx_1 = o[field] ~= nil; end
      return _hx_1
    end )()) then 
      do return String.prototype[k] end;
    else
      if (String.__oldindex ~= nil) then 
        if (_G.type(String.__oldindex) == "function") then 
          do return String.__oldindex(s, k) end;
        else
          if (_G.type(String.__oldindex) == "table") then 
            do return String.__oldindex[k] end;
          end;
        end;
        do return nil end;
      else
        do return nil end;
      end;
    end;
  end;
end
String.indexOfEmpty = function(s,startIndex) 
  local length = _G.string.len(s);
  if (startIndex < 0) then 
    startIndex = length + startIndex;
    if (startIndex < 0) then 
      startIndex = 0;
    end;
  end;
  if (startIndex > length) then 
    do return length end;
  else
    do return startIndex end;
  end;
end
String.fromCharCode = function(code) 
  do return _G.string.char(code) end;
end
String.prototype = _hx_e();
String.prototype.toUpperCase = function(self) 
  do return _G.string.upper(self) end
end
String.prototype.toLowerCase = function(self) 
  do return _G.string.lower(self) end
end
String.prototype.indexOf = function(self,str,startIndex) 
  if (startIndex == nil) then 
    startIndex = 1;
  else
    startIndex = startIndex + 1;
  end;
  if (str == "") then 
    do return String.indexOfEmpty(self, startIndex - 1) end;
  end;
  local r = _G.string.find(self, str, startIndex, true);
  if ((r ~= nil) and (r > 0)) then 
    do return r - 1 end;
  else
    do return -1 end;
  end;
end
String.prototype.lastIndexOf = function(self,str,startIndex) 
  local ret = -1;
  if (startIndex == nil) then 
    startIndex = #self;
  end;
  while (true) do _hx_do_first_1 = false;
    
    local p = String.prototype.indexOf(self, str, ret + 1);
    if (((p == -1) or (p > startIndex)) or (p == ret)) then 
      break;
    end;
    ret = p;
  end;
  do return ret end
end
String.prototype.split = function(self,delimiter) 
  local idx = 1;
  local ret = _hx_tab_array({}, 0);
  while (idx ~= nil) do _hx_do_first_1 = false;
    
    local newidx = 0;
    if (#delimiter > 0) then 
      newidx = _G.string.find(self, delimiter, idx, true);
    else
      if (idx >= #self) then 
        newidx = nil;
      else
        newidx = idx + 1;
      end;
    end;
    if (newidx ~= nil) then 
      local match = _G.string.sub(self, idx, newidx - 1);
      ret:push(match);
      idx = newidx + #delimiter;
    else
      ret:push(_G.string.sub(self, idx, #self));
      idx = nil;
    end;
  end;
  do return ret end
end
String.prototype.toString = function(self) 
  do return self end
end
String.prototype.substring = function(self,startIndex,endIndex) 
  if (endIndex == nil) then 
    endIndex = #self;
  end;
  if (endIndex < 0) then 
    endIndex = 0;
  end;
  if (startIndex < 0) then 
    startIndex = 0;
  end;
  if (endIndex < startIndex) then 
    do return _G.string.sub(self, endIndex + 1, startIndex) end;
  else
    do return _G.string.sub(self, startIndex + 1, endIndex) end;
  end;
end
String.prototype.charAt = function(self,index) 
  do return _G.string.sub(self, index + 1, index + 1) end
end
String.prototype.charCodeAt = function(self,index) 
  do return _G.string.byte(self, index + 1) end
end
String.prototype.substr = function(self,pos,len) 
  if ((len == nil) or (len > (pos + #self))) then 
    len = #self;
  else
    if (len < 0) then 
      len = #self + len;
    end;
  end;
  if (pos < 0) then 
    pos = #self + pos;
  end;
  if (pos < 0) then 
    pos = 0;
  end;
  do return _G.string.sub(self, pos + 1, pos + len) end
end

String.prototype.__class__ =  String

Std.new = {}
Std.__name__ = true
Std.string = function(s) 
  do return _hx_tostring(s, 0) end;
end
Std.int = function(x) 
  if (not Math.isFinite(x) or Math.isNaN(x)) then 
    do return 0 end;
  else
    do return _hx_bit_clamp(x) end;
  end;
end

__haxe_Exception.new = function(message,previous,native) 
  local self = _hx_new(__haxe_Exception.prototype)
  __haxe_Exception.super(self,message,previous,native)
  return self
end
__haxe_Exception.super = function(self,message,previous,native) 
  self.__skipStack = 0;
  self.__exceptionMessage = message;
  self.__previousException = previous;
  if (native ~= nil) then 
    self.__nativeException = native;
    self.__nativeStack = __haxe_NativeStackTrace.exceptionStack();
  else
    self.__nativeException = self;
    self.__nativeStack = __haxe_NativeStackTrace.callStack();
    self.__skipStack = 1;
  end;
end
__haxe_Exception.__name__ = true
__haxe_Exception.prototype = _hx_e();
__haxe_Exception.prototype.toString = function(self) 
  do return self:get_message() end
end
__haxe_Exception.prototype.get_message = function(self) 
  do return self.__exceptionMessage end
end

__haxe_Exception.prototype.__class__ =  __haxe_Exception

__haxe_Log.new = {}
__haxe_Log.__name__ = true
__haxe_Log.formatOutput = function(v,infos) 
  local str = Std.string(v);
  if (infos == nil) then 
    do return str end;
  end;
  local pstr = Std.string(Std.string(infos.fileName) .. Std.string(":")) .. Std.string(infos.lineNumber);
  if (infos.customParams ~= nil) then 
    local _g = 0;
    local _g1 = infos.customParams;
    while (_g < _g1.length) do _hx_do_first_1 = false;
      
      local v = _g1[_g];
      _g = _g + 1;
      str = Std.string(str) .. Std.string((Std.string(", ") .. Std.string(Std.string(v))));
    end;
  end;
  do return Std.string(Std.string(pstr) .. Std.string(": ")) .. Std.string(str) end;
end
__haxe_Log.trace = function(v,infos) 
  local str = __haxe_Log.formatOutput(v, infos);
  _hx_print(str);
end

__haxe_NativeStackTrace.new = {}
__haxe_NativeStackTrace.__name__ = true
__haxe_NativeStackTrace.saveStack = function(exception) 
end
__haxe_NativeStackTrace.callStack = function() 
  local _g = debug.traceback();
  if (_g == nil) then 
    do return _hx_tab_array({}, 0) end;
  else
    local s = _g;
    do return String.prototype.split(s, "\n"):slice(3) end;
  end;
end
__haxe_NativeStackTrace.exceptionStack = function() 
  do return _hx_tab_array({}, 0) end;
end

__haxe_ValueException.new = function(value,previous,native) 
  local self = _hx_new(__haxe_ValueException.prototype)
  __haxe_ValueException.super(self,value,previous,native)
  return self
end
__haxe_ValueException.super = function(self,value,previous,native) 
  __haxe_Exception.super(self,(function() 
    local _hx_1
    if (value == nil) then 
    _hx_1 = "null"; else 
    _hx_1 = Std.string(value); end
    return _hx_1
  end )(),previous,native);
  self.value = value;
end
__haxe_ValueException.__name__ = true
__haxe_ValueException.prototype = _hx_e();

__haxe_ValueException.prototype.__class__ =  __haxe_ValueException
__haxe_ValueException.__super__ = __haxe_Exception
setmetatable(__haxe_ValueException.prototype,{__index=__haxe_Exception.prototype})

__haxe_exceptions_PosException.new = function(message,previous,pos) 
  local self = _hx_new(__haxe_exceptions_PosException.prototype)
  __haxe_exceptions_PosException.super(self,message,previous,pos)
  return self
end
__haxe_exceptions_PosException.super = function(self,message,previous,pos) 
  __haxe_Exception.super(self,message,previous);
  if (pos == nil) then 
    self.posInfos = _hx_o({__fields__={fileName=true,lineNumber=true,className=true,methodName=true},fileName="(unknown)",lineNumber=0,className="(unknown)",methodName="(unknown)"});
  else
    self.posInfos = pos;
  end;
end
__haxe_exceptions_PosException.__name__ = true
__haxe_exceptions_PosException.prototype = _hx_e();
__haxe_exceptions_PosException.prototype.toString = function(self) 
  do return Std.string(Std.string(Std.string(Std.string(Std.string(Std.string(Std.string(Std.string(Std.string("") .. Std.string(__haxe_Exception.prototype.toString(self))) .. Std.string(" in ")) .. Std.string(self.posInfos.className)) .. Std.string(".")) .. Std.string(self.posInfos.methodName)) .. Std.string(" at ")) .. Std.string(self.posInfos.fileName)) .. Std.string(":")) .. Std.string(self.posInfos.lineNumber) end
end

__haxe_exceptions_PosException.prototype.__class__ =  __haxe_exceptions_PosException
__haxe_exceptions_PosException.__super__ = __haxe_Exception
setmetatable(__haxe_exceptions_PosException.prototype,{__index=__haxe_Exception.prototype})

__haxe_exceptions_NotImplementedException.new = function(message,previous,pos) 
  local self = _hx_new(__haxe_exceptions_NotImplementedException.prototype)
  __haxe_exceptions_NotImplementedException.super(self,message,previous,pos)
  return self
end
__haxe_exceptions_NotImplementedException.super = function(self,message,previous,pos) 
  if (message == nil) then 
    message = "Not implemented";
  end;
  __haxe_exceptions_PosException.super(self,message,previous,pos);
end
__haxe_exceptions_NotImplementedException.__name__ = true
__haxe_exceptions_NotImplementedException.prototype = _hx_e();

__haxe_exceptions_NotImplementedException.prototype.__class__ =  __haxe_exceptions_NotImplementedException
__haxe_exceptions_NotImplementedException.__super__ = __haxe_exceptions_PosException
setmetatable(__haxe_exceptions_NotImplementedException.prototype,{__index=__haxe_exceptions_PosException.prototype})

__haxe_iterators_ArrayIterator.new = function(array) 
  local self = _hx_new(__haxe_iterators_ArrayIterator.prototype)
  __haxe_iterators_ArrayIterator.super(self,array)
  return self
end
__haxe_iterators_ArrayIterator.super = function(self,array) 
  self.current = 0;
  self.array = array;
end
__haxe_iterators_ArrayIterator.__name__ = true
__haxe_iterators_ArrayIterator.prototype = _hx_e();
__haxe_iterators_ArrayIterator.prototype.hasNext = function(self) 
  do return self.current < self.array.length end
end
__haxe_iterators_ArrayIterator.prototype.next = function(self) 
  do return self.array[(function() 
  local _hx_obj = self;
  local _hx_fld = 'current';
  local _ = _hx_obj[_hx_fld];
  _hx_obj[_hx_fld] = _hx_obj[_hx_fld]  + 1;
   return _;
   end)()] end
end

__haxe_iterators_ArrayIterator.prototype.__class__ =  __haxe_iterators_ArrayIterator

__haxe_iterators_ArrayKeyValueIterator.new = function(array) 
  local self = _hx_new(__haxe_iterators_ArrayKeyValueIterator.prototype)
  __haxe_iterators_ArrayKeyValueIterator.super(self,array)
  return self
end
__haxe_iterators_ArrayKeyValueIterator.super = function(self,array) 
  self.array = array;
end
__haxe_iterators_ArrayKeyValueIterator.__name__ = true
__haxe_iterators_ArrayKeyValueIterator.prototype = _hx_e();

__haxe_iterators_ArrayKeyValueIterator.prototype.__class__ =  __haxe_iterators_ArrayKeyValueIterator

__koneko_core_InstanceObject.new = {}
__koneko_core_InstanceObject.__name__ = true
__koneko_core_InstanceObject.prototype = _hx_e();

__koneko_core_InstanceObject.prototype.__class__ =  __koneko_core_InstanceObject
_hxClasses["koneko.godot.Vector2Axis"] = { __ename__ = true, __constructs__ = _hx_tab_array({[0]="X","Y"},2)}
__koneko_godot_Vector2Axis = _hxClasses["koneko.godot.Vector2Axis"];
__koneko_godot_Vector2Axis.X = _hx_tab_array({[0]="X",0,__enum__ = __koneko_godot_Vector2Axis},2)

__koneko_godot_Vector2Axis.Y = _hx_tab_array({[0]="Y",1,__enum__ = __koneko_godot_Vector2Axis},2)


__koneko_godot_Vector2.new = function(x,y) 
  local self = _hx_new(__koneko_godot_Vector2.prototype)
  __koneko_godot_Vector2.super(self,x,y)
  return self
end
__koneko_godot_Vector2.super = function(self,x,y) 
  self.instance = godot.Vector2.__new(x, y);
end
__koneko_godot_Vector2.__name__ = true
__koneko_godot_Vector2.fromInstance = function(instance) 
  local vector2 = __koneko_godot_Vector2.new(0, 0);
  vector2.instance = instance;
  do return vector2 end;
end
__koneko_godot_Vector2.prototype = _hx_e();
__koneko_godot_Vector2.prototype.get_x = function(self) 
  local untypedX = self.instance.x;
  do return untypedX end
end
__koneko_godot_Vector2.prototype.set_x = function(self,value) 
  self.instance.x = value;
  do return value end
end
__koneko_godot_Vector2.prototype.get_y = function(self) 
  local untypedY = self.instance.y;
  do return untypedY end
end
__koneko_godot_Vector2.prototype.set_y = function(self,value) 
  self.instance.y = value;
  do return value end
end
__koneko_godot_Vector2.prototype.abs = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:abs()) end
end
__koneko_godot_Vector2.prototype.angle = function(self) 
  do return self.instance:angle() end
end
__koneko_godot_Vector2.prototype.angleTo = function(self,point) 
  do return self.instance:angleTo(point.instance) end
end
__koneko_godot_Vector2.prototype.angleToPoint = function(self,point) 
  do return self.instance:angleToPoint(point.instance) end
end
__koneko_godot_Vector2.prototype.aspect = function(self) 
  do return self.instance:aspect() end
end
__koneko_godot_Vector2.prototype.bounce = function(self,n) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:bounce(n.instance)) end
end
__koneko_godot_Vector2.prototype.ceil = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:ceil()) end
end
__koneko_godot_Vector2.prototype.cross = function(self,b) 
  do return self.instance:cross(b.instance) end
end
__koneko_godot_Vector2.prototype.cubicInterpolate = function(self,b,preA,postB,weight) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:cubicInterpolate(b.instance, preA.instance, postB.instance, weight)) end
end
__koneko_godot_Vector2.prototype.directionTo = function(self,b) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:directionTo(b.instance)) end
end
__koneko_godot_Vector2.prototype.dot = function(self,with) 
  do return self.instance:dot(with.instance) end
end
__koneko_godot_Vector2.prototype.floor = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:floor()) end
end
__koneko_godot_Vector2.prototype.inverse = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:inverse()) end
end
__koneko_godot_Vector2.prototype.isNormalized = function(self) 
  do return self.instance:isNormalized() end
end
__koneko_godot_Vector2.prototype.length = function(self) 
  do return _hx_wrap_if_string_field(self.instance,'length')(self.instance) end
end
__koneko_godot_Vector2.prototype.lengthSquared = function(self) 
  do return self.instance:lengthSquared() end
end
__koneko_godot_Vector2.prototype.linearInterpolatef = function(self,b,t) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:linearInterpolate(b.instance, t)) end
end
__koneko_godot_Vector2.prototype.linearInterpolate = function(self,to,weight) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:linearInterpolate(to.instance, weight.instance)) end
end
__koneko_godot_Vector2.prototype.limitLength = function(self,length) 
  if (length == nil) then 
    length = 1;
  end;
  do return __koneko_godot_Vector2.fromInstance(self.instance:limitLength(length)) end
end
__koneko_godot_Vector2.prototype.maxAxis = function(self) 
  local axis = self.instance:maxAxis();
  if (axis == 0) then 
    do return __koneko_godot_Vector2Axis.X end;
  else
    do return __koneko_godot_Vector2Axis.Y end;
  end;
end
__koneko_godot_Vector2.prototype.minAxis = function(self) 
  local axis = self.instance:minAxis();
  if (axis == 0) then 
    do return __koneko_godot_Vector2Axis.X end;
  else
    do return __koneko_godot_Vector2Axis.Y end;
  end;
end
__koneko_godot_Vector2.prototype.moveToward = function(self,to,delta) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:moveToward(to.instance, delta)) end
end
__koneko_godot_Vector2.prototype.normalized = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:normalized()) end
end
__koneko_godot_Vector2.prototype.perpendicular = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:perpendicular()) end
end
__koneko_godot_Vector2.prototype.posModf = function(self,mod) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:posMod(mod)) end
end
__koneko_godot_Vector2.prototype.posMod = function(self,mod) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:posMod(mod.instance)) end
end
__koneko_godot_Vector2.prototype.project = function(self,b) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:project(b.instance)) end
end
__koneko_godot_Vector2.prototype.reflect = function(self,n) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:reflect(n.instance)) end
end
__koneko_godot_Vector2.prototype.rotated = function(self,angle) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:rotated(angle)) end
end
__koneko_godot_Vector2.prototype.round = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:round()) end
end
__koneko_godot_Vector2.prototype.sign = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:sign()) end
end
__koneko_godot_Vector2.prototype.slerp = function(self,to,weight) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:slerp(to.instance, weight)) end
end
__koneko_godot_Vector2.prototype.slide = function(self,n) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:slide(n.instance)) end
end
__koneko_godot_Vector2.prototype.snapped = function(self,by) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:snapped(by.instance)) end
end
__koneko_godot_Vector2.prototype.tangent = function(self) 
  do return __koneko_godot_Vector2.fromInstance(self.instance:tangent()) end
end
__koneko_godot_Vector2.prototype.add = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(_hx_dyn_add(self.instance,rhs.instance)) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance + rhs) end;
  end;
end
__koneko_godot_Vector2.prototype.subtract = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(self.instance - rhs.instance) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance - rhs) end;
  end;
end
__koneko_godot_Vector2.prototype.multiply = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(self.instance * rhs.instance) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance * rhs) end;
  end;
end
__koneko_godot_Vector2.prototype.divide = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(self.instance / rhs.instance) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance / rhs) end;
  end;
end
__koneko_godot_Vector2.prototype.modulo = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(_G.math.fmod(self.instance, rhs.instance)) end;
  else
    do return __koneko_godot_Vector3.fromInstance(_G.math.fmod(self.instance, rhs)) end;
  end;
end
__koneko_godot_Vector2.prototype.equal = function(self,rhs) 
  do return self.instance == rhs.instance end
end
__koneko_godot_Vector2.prototype.noequal = function(self,rhs) 
  do return self.instance ~= rhs.instance end
end
__koneko_godot_Vector2.prototype.lessthan = function(self,rhs) 
  do return self.instance < rhs.instance end
end
__koneko_godot_Vector2.prototype.lessthanequal = function(self,rhs) 
  do return self.instance <= rhs.instance end
end
__koneko_godot_Vector2.prototype.greaterthan = function(self,rhs) 
  do return self.instance > rhs.instance end
end
__koneko_godot_Vector2.prototype.greaterthanequal = function(self,rhs) 
  do return self.instance >= rhs.instance end
end
__koneko_godot_Vector2.prototype.isEqualApprox = function(self,other) 
  do return self.instance:isEqualApprox(other.instance) end
end
__koneko_godot_Vector2.prototype.isZeroApprox = function(self) 
  do return self.instance:isZeroApprox() end
end
__koneko_godot_Vector2.prototype.toString = function(self) 
  do return self.instance.toString() end
end

__koneko_godot_Vector2.prototype.__class__ =  __koneko_godot_Vector2
__koneko_godot_Vector2.__super__ = __koneko_core_InstanceObject
setmetatable(__koneko_godot_Vector2.prototype,{__index=__koneko_core_InstanceObject.prototype})
_hxClasses["koneko.godot.Vector3Axis"] = { __ename__ = true, __constructs__ = _hx_tab_array({[0]="X","Y","Z"},3)}
__koneko_godot_Vector3Axis = _hxClasses["koneko.godot.Vector3Axis"];
__koneko_godot_Vector3Axis.X = _hx_tab_array({[0]="X",0,__enum__ = __koneko_godot_Vector3Axis},2)

__koneko_godot_Vector3Axis.Y = _hx_tab_array({[0]="Y",1,__enum__ = __koneko_godot_Vector3Axis},2)

__koneko_godot_Vector3Axis.Z = _hx_tab_array({[0]="Z",2,__enum__ = __koneko_godot_Vector3Axis},2)


__koneko_godot_Vector3.new = function(x,y,z) 
  local self = _hx_new(__koneko_godot_Vector3.prototype)
  __koneko_godot_Vector3.super(self,x,y,z)
  return self
end
__koneko_godot_Vector3.super = function(self,x,y,z) 
  if (z == nil) then 
    z = 0;
  end;
  if (y == nil) then 
    y = 0;
  end;
  if (x == nil) then 
    x = 0;
  end;
  self.instance = godot.Vector3.__new(x, y, z);
end
__koneko_godot_Vector3.__name__ = true
__koneko_godot_Vector3.fromInstance = function(instance) 
  local vector3 = __koneko_godot_Vector3.new();
  vector3.instance = instance;
  do return vector3 end;
end
__koneko_godot_Vector3.prototype = _hx_e();
__koneko_godot_Vector3.prototype.get_x = function(self) 
  local untypedX = self.instance.x;
  do return untypedX end
end
__koneko_godot_Vector3.prototype.set_x = function(self,value) 
  self.instance.x = value;
  do return value end
end
__koneko_godot_Vector3.prototype.get_y = function(self) 
  local untypedY = self.instance.y;
  do return untypedY end
end
__koneko_godot_Vector3.prototype.set_y = function(self,value) 
  self.instance.y = value;
  do return value end
end
__koneko_godot_Vector3.prototype.get_z = function(self) 
  local untypedZ = self.instance.z;
  do return untypedZ end
end
__koneko_godot_Vector3.prototype.set_z = function(self,value) 
  self.instance.z = value;
  do return value end
end
__koneko_godot_Vector3.prototype.abs = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:abs()) end
end
__koneko_godot_Vector3.prototype.angleTo = function(self,to) 
  do return self.instance:angleTo(to.instance) end
end
__koneko_godot_Vector3.prototype.angleToPoint = function(self,to) 
  do return self.instance:angleToPoint(to.instance) end
end
__koneko_godot_Vector3.prototype.bounce = function(self,n) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:bounce(n.instance)) end
end
__koneko_godot_Vector3.prototype.ceil = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:ceil()) end
end
__koneko_godot_Vector3.prototype.cross = function(self,b) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:cross(b.instance)) end
end
__koneko_godot_Vector3.prototype.cubicInterpolate = function(self,b,preA,postB,weight) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:cubicInterpolate(b.instance, preA.instance, postB.instance, weight)) end
end
__koneko_godot_Vector3.prototype.directionTo = function(self,to) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:directionTo(to.instance)) end
end
__koneko_godot_Vector3.prototype.distanceTo = function(self,to) 
  do return self.instance:distanceTo(to.instance) end
end
__koneko_godot_Vector3.prototype.distanceSquaredTo = function(self,to) 
  do return self.instance:distanceSquaredTo(to.instance) end
end
__koneko_godot_Vector3.prototype.dot = function(self,with) 
  do return self.instance:dot(with.instance) end
end
__koneko_godot_Vector3.prototype.floor = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:floor()) end
end
__koneko_godot_Vector3.prototype.inverse = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:inverse()) end
end
__koneko_godot_Vector3.prototype.isNormalized = function(self) 
  do return self.instance:isNormalized() end
end
__koneko_godot_Vector3.prototype.length = function(self) 
  do return _hx_wrap_if_string_field(self.instance,'length')(self.instance) end
end
__koneko_godot_Vector3.prototype.lengthSquared = function(self) 
  do return self.instance:lengthSquared() end
end
__koneko_godot_Vector3.prototype.linearInterpolate = function(self,to,weight) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:linearInterpolate(to.instance, weight)) end
end
__koneko_godot_Vector3.prototype.limitLength = function(self,length) 
  if (length == nil) then 
    length = 1;
  end;
  do return self.instance:limitLength(length) end
end
__koneko_godot_Vector3.prototype.maxAxis = function(self) 
  local val = self.instance:maxAxis();
  if (val == 0) then 
    do return __koneko_godot_Vector3Axis.X end;
  else
    if (val == 1) then 
      do return __koneko_godot_Vector3Axis.Y end;
    else
      do return __koneko_godot_Vector3Axis.Z end;
    end;
  end;
end
__koneko_godot_Vector3.prototype.minAxis = function(self) 
  local val = self.instance:minAxis();
  if (val == 0) then 
    do return __koneko_godot_Vector3Axis.X end;
  else
    if (val == 1) then 
      do return __koneko_godot_Vector3Axis.Y end;
    else
      do return __koneko_godot_Vector3Axis.Z end;
    end;
  end;
end
__koneko_godot_Vector3.prototype.moveToward = function(self,to,delta) 
  do return self.instance:moveToward(to.instance, delta) end
end
__koneko_godot_Vector3.prototype.normalized = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:normalized()) end
end
__koneko_godot_Vector3.prototype.outer = function(self,with) 
  do return self.instance:outer(with.instance) end
end
__koneko_godot_Vector3.prototype.posModf = function(self,mod) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:posMod(mod)) end
end
__koneko_godot_Vector3.prototype.posMod = function(self,modv) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:posMod(modv.instance)) end
end
__koneko_godot_Vector3.prototype.project = function(self,onNormal) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:project(onNormal.instance)) end
end
__koneko_godot_Vector3.prototype.reflect = function(self,normal) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:reflect(normal.instance)) end
end
__koneko_godot_Vector3.prototype.rotated = function(self,axis,angle) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:rotated(axis.instance, angle)) end
end
__koneko_godot_Vector3.prototype.round = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:round()) end
end
__koneko_godot_Vector3.prototype.sign = function(self) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:sign()) end
end
__koneko_godot_Vector3.prototype.signedAngleTo = function(self,to,axis) 
  do return self.instance:signedAngleTo(to.instance, axis.instance) end
end
__koneko_godot_Vector3.prototype.slerp = function(self,to,weight) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:slerp(to.instance, weight)) end
end
__koneko_godot_Vector3.prototype.slide = function(self,normal) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:slide(normal.instance)) end
end
__koneko_godot_Vector3.prototype.snapped = function(self,step) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:snapped(step.instance)) end
end
__koneko_godot_Vector3.prototype.snappedf = function(self,step) 
  do return __koneko_godot_Vector3.fromInstance(self.instance:snapped(step)) end
end
__koneko_godot_Vector3.prototype.add = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(_hx_dyn_add(self.instance,rhs.instance)) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance + rhs) end;
  end;
end
__koneko_godot_Vector3.prototype.subtract = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(self.instance - rhs.instance) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance - rhs) end;
  end;
end
__koneko_godot_Vector3.prototype.multiply = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(self.instance * rhs.instance) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance * rhs) end;
  end;
end
__koneko_godot_Vector3.prototype.divide = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(self.instance / rhs.instance) end;
  else
    do return __koneko_godot_Vector3.fromInstance(self.instance / rhs) end;
  end;
end
__koneko_godot_Vector3.prototype.modulo = function(self,rhs) 
  if (__lua_Boot.__instanceof(rhs, __koneko_godot_Vector3)) then 
    do return __koneko_godot_Vector3.fromInstance(_G.math.fmod(self.instance, rhs.instance)) end;
  else
    do return __koneko_godot_Vector3.fromInstance(_G.math.fmod(self.instance, rhs)) end;
  end;
end
__koneko_godot_Vector3.prototype.equal = function(self,rhs) 
  do return self.instance == rhs.instance end
end
__koneko_godot_Vector3.prototype.noequal = function(self,rhs) 
  do return self.instance ~= rhs.instance end
end
__koneko_godot_Vector3.prototype.lessthan = function(self,rhs) 
  do return self.instance < rhs.instance end
end
__koneko_godot_Vector3.prototype.lessthanequal = function(self,rhs) 
  do return self.instance <= rhs.instance end
end
__koneko_godot_Vector3.prototype.greaterthan = function(self,rhs) 
  do return self.instance > rhs.instance end
end
__koneko_godot_Vector3.prototype.greaterthanequal = function(self,rhs) 
  do return self.instance >= rhs.instance end
end
__koneko_godot_Vector3.prototype.equals = function(self,other) 
  do return self.instance:equals(other.instance) end
end
__koneko_godot_Vector3.prototype.isEqualApprox = function(self,other) 
  do return self.instance:isEqualApprox(other.instance) end
end
__koneko_godot_Vector3.prototype.isZeroApprox = function(self) 
  do return self.instance:isZeroApprox() end
end
__koneko_godot_Vector3.prototype.toString = function(self) 
  do return self.instance.toString() end
end

__koneko_godot_Vector3.prototype.__class__ =  __koneko_godot_Vector3
__koneko_godot_Vector3.__super__ = __koneko_core_InstanceObject
setmetatable(__koneko_godot_Vector3.prototype,{__index=__koneko_core_InstanceObject.prototype})

__lua_Boot.new = {}
__lua_Boot.__name__ = true
__lua_Boot.__instanceof = function(o,cl) 
  if (cl == nil) then 
    do return false end;
  end;
  local cl1 = cl;
  if (cl1) == Array then 
    do return __lua_Boot.isArray(o) end;
  elseif (cl1) == Bool then 
    do return _G.type(o) == "boolean" end;
  elseif (cl1) == Dynamic then 
    do return o ~= nil end;
  elseif (cl1) == Float then 
    do return _G.type(o) == "number" end;
  elseif (cl1) == Int then 
    if (_G.type(o) == "number") then 
      do return _hx_bit_clamp(o) == o end;
    else
      do return false end;
    end;
  elseif (cl1) == String then 
    do return _G.type(o) == "string" end;
  elseif (cl1) == _G.table then 
    do return _G.type(o) == "table" end;
  elseif (cl1) == __lua_Thread then 
    do return _G.type(o) == "thread" end;
  elseif (cl1) == __lua_UserData then 
    do return _G.type(o) == "userdata" end;else
  if (((o ~= nil) and (_G.type(o) == "table")) and (_G.type(cl) == "table")) then 
    local tmp;
    if (__lua_Boot.__instanceof(o, Array)) then 
      tmp = Array;
    else
      if (__lua_Boot.__instanceof(o, String)) then 
        tmp = String;
      else
        local cl = o.__class__;
        tmp = (function() 
          local _hx_1
          if (cl ~= nil) then 
          _hx_1 = cl; else 
          _hx_1 = nil; end
          return _hx_1
        end )();
      end;
    end;
    if (__lua_Boot.extendsOrImplements(tmp, cl)) then 
      do return true end;
    end;
    if ((function() 
      local _hx_2
      if (cl == Class) then 
      _hx_2 = o.__name__ ~= nil; else 
      _hx_2 = false; end
      return _hx_2
    end )()) then 
      do return true end;
    end;
    if ((function() 
      local _hx_3
      if (cl == Enum) then 
      _hx_3 = o.__ename__ ~= nil; else 
      _hx_3 = false; end
      return _hx_3
    end )()) then 
      do return true end;
    end;
    do return o.__enum__ == cl end;
  else
    do return false end;
  end; end;
end
__lua_Boot.isArray = function(o) 
  if (_G.type(o) == "table") then 
    if ((o.__enum__ == nil) and (_G.getmetatable(o) ~= nil)) then 
      do return _G.getmetatable(o).__index == Array.prototype end;
    else
      do return false end;
    end;
  else
    do return false end;
  end;
end
__lua_Boot.extendsOrImplements = function(cl1,cl2) 
  if ((cl1 == nil) or (cl2 == nil)) then 
    do return false end;
  else
    if (cl1 == cl2) then 
      do return true end;
    else
      if (cl1.__interfaces__ ~= nil) then 
        local intf = cl1.__interfaces__;
        local _g = 1;
        local _g1 = _hx_table.maxn(intf) + 1;
        while (_g < _g1) do _hx_do_first_1 = false;
          
          _g = _g + 1;
          local i = _g - 1;
          if (__lua_Boot.extendsOrImplements(intf[i], cl2)) then 
            do return true end;
          end;
        end;
      end;
    end;
  end;
  do return __lua_Boot.extendsOrImplements(cl1.__super__, cl2) end;
end

__lua_UserData.new = {}
__lua_UserData.__name__ = true

__lua_Thread.new = {}
__lua_Thread.__name__ = true
if _hx_bit_raw then
    _hx_bit_clamp = function(v)
    if v <= 2147483647 and v >= -2147483648 then
        if v > 0 then return _G.math.floor(v)
        else return _G.math.ceil(v)
        end
    end
    if v > 2251798999999999 then v = v*2 end;
    if (v ~= v or math.abs(v) == _G.math.huge) then return nil end
    return _hx_bit_raw.band(v, 2147483647 ) - math.abs(_hx_bit_raw.band(v, 2147483648))
    end
else
    _hx_bit_clamp = function(v)
        if v < -2147483648 then
            return -2147483648
        elseif v > 2147483647 then
            return 2147483647
        elseif v > 0 then
            return _G.math.floor(v)
        else
            return _G.math.ceil(v)
        end
    end
end;



_hx_array_mt.__index = Array.prototype

if package.loaded.luv then
  _hx_luv = _G.require("luv");
else
  _hx_luv = {
    run=function(mode) return false end,
    loop_alive=function() return false end
  }
end
local _hx_static_init = function()
  
  String.__name__ = true;
  Array.__name__ = true;__koneko_godot_Vector3.ZERO = __koneko_godot_Vector3.new(0, 0, 0);
  
  __koneko_godot_Vector3.ONE = __koneko_godot_Vector3.new(1, 1, 1);
  
  __koneko_godot_Vector3.INF = godot.Vector3.inf;
  
  __koneko_godot_Vector3.UP = __koneko_godot_Vector3.new(0, 1, 0);
  
  __koneko_godot_Vector3.DOWN = __koneko_godot_Vector3.new(0, -1, 0);
  
  __koneko_godot_Vector3.LEFT = __koneko_godot_Vector3.new(-1, 0, 0);
  
  __koneko_godot_Vector3.RIGHT = __koneko_godot_Vector3.new(1, 0, 0);
  
  __koneko_godot_Vector3.FORWARD = __koneko_godot_Vector3.new(0, 0, -1);
  
  __koneko_godot_Vector3.BACK = __koneko_godot_Vector3.new(0, 0, 1);
  
  __koneko_godot_Vector3.MODEL_LEFT = __koneko_godot_Vector3.new(1, 0, 0);
  
  __koneko_godot_Vector3.MODEL_RIGHT = __koneko_godot_Vector3.new(-1, 0, 0);
  
  __koneko_godot_Vector3.MODEL_TOP = __koneko_godot_Vector3.new(0, 1, 0);
  
  __koneko_godot_Vector3.MODEL_BOTTOM = __koneko_godot_Vector3.new(0, -1, 0);
  
  __koneko_godot_Vector3.MODEL_FRONT = __koneko_godot_Vector3.new(0, 0, 1);
  
  __koneko_godot_Vector3.MODEL_REAR = __koneko_godot_Vector3.new(0, 0, -1);
  
  
end

_hx_print = print or (function() end)

_hx_table = {}
_hx_table.pack = _G.table.pack or function(...)
    return {...}
end
_hx_table.unpack = _G.table.unpack or _G.unpack
_hx_table.maxn = _G.table.maxn or function(t)
  local maxn=0;
  for i in pairs(t) do
    maxn=type(i)=='number'and i>maxn and i or maxn
  end
  return maxn
end;

_hx_wrap_if_string_field = function(o, fld)
  if _G.type(o) == 'string' then
    if fld == 'length' then
      return _G.string.len(o)
    else
      return String.prototype[fld]
    end
  else
    return o[fld]
  end
end

_hx_dyn_add = function(a,b)
  if (_G.type(a) == 'string' or _G.type(b) == 'string') then
    return Std.string(a)..Std.string(b)
  else
    return a + b;
  end;
end;

function _hx_handle_error(obj)
  local message = tostring(obj)
  if _G.debug and _G.debug.traceback then
    -- level 2 to skip _hx_handle_error
    message = _G.debug.traceback(message, 2)
  end
  return setmetatable({}, { __tostring = function() return message end })
end

_hx_static_init();
local success, err = _G.xpcall(function() 
  Main.main();
  _hx_luv.run();
end, _hx_handle_error)
if not success then _G.error(err) end
