package lucidKit.godot;

@:native("godot.Material3D")
extern class Material3D extends Material {
    public var albedoColor: Color;
    public var albedoTexture: Texture;
    public var anisotropy: Float;
    public var anisotropyEnabled: Bool;
    public var anisotropyFlowmap: Texture;
    public var aoEnabled: Bool;
    public var aoLightAffect: Float;
    public var aoOnUv2: Bool;
    public var aoTexture: Texture;
    public var aoTextureChannel: Int;
    public var asyncMode: Int;
    public var clearcoat: Float;
    public var clearcoatEnabled: Bool;
    public var clearcoatGloss: Float;
    public var clearcoatTexture: Texture;
    public var depthDeepParallax: Bool;
    public var depthEnabled: Bool;
    public var depthFlipBinormal: Bool;
    public var depthFlipTangent: Bool;
    public var depthMaxLayers: Int;
    public var depthMinLayers: Int;
    public var depthScale: Float;
    public var depthTexture: Texture;
    public var detailAlbedo: Texture;
    public var detailBlendMode: Int;
    public var detailEnabled: Bool;
    public var detailMask: Texture;
    public var detailNormal: Texture;
    public var detailUvLayer: Int;
    public var distanceFadeMaxDistance: Float;
    public var distanceFadeMinDistance: Float;
    public var distanceFadeMode: Int;
    public var emission: Color;
    public var emissionEnabled: Bool;
    public var emissionEnergy: Float;
    public var emissionOnUv2: Bool;
    public var emissionOperator: Int;
    public var emissionTexture: Texture;
    public var flagsAlbedoTexForceSrgb: Bool;
    public var flagsAlbedoTexMsdf: Bool;
    public var flagsDisableAmbientLight: Bool;
    public var flagsDoNotReceiveShadows: Bool;
    public var flagsEnsureCorrectNormals: Bool;
    public var flagsFixedSize: Bool;
    public var flagsNoDepthTest: Bool;
    public var flagsTransparent: Bool;
    public var flagsUnshaded: Bool;
    public var flagsUsePointSize: Bool;
    public var flagsUseShadowToOpacity: Bool;
    public var flagsVertexLighting: Bool;
    public var flagsWorldTriplanar: Bool;
    public var metallic: Float;
    public var metallicSpecular: Float;
    public var metallicTexture: Texture;
    public var metallicTextureChannel: Int;
    public var normalEnabled: Bool;
    public var normalScale: Float;
    public var normalTexture: Texture;
    public var ormTexture: Texture;
    public var paramsAlphaScissorThreshold: Float;
    public var paramsBillboardKeepScale: Bool;
    public var paramsBillboardMode: Int;
    public var paramsBlendMode: Int;
    public var paramsCullMode: Int;
    public var paramsDepthDrawMode: Int;
    public var paramsDiffuseMode: Int;
    public var paramsGrow: Bool;
    public var paramsGrowAmount: Float;
    public var paramsLineWidth: Float;
    public var paramsPointSize: Float;
    public var paramsSpecularMode: Int;
    public var paramsUseAlphaScissor: Bool;
    public var particlesAnimHFrames: Int;
    public var particlesAnimLoop: Bool;
    public var particlesAnimVFrames: Int;
    public var proximityFadeDistance: Float;
    public var proximityFadeEnable: Bool;
    public var refractionEnabled: Bool;
    public var refractionScale: Float;
    public var refractionTexture: Texture;
    public var refractionTextureChannel: Int;
    public var rim: Float;
    public var rimEnabled: Bool;
    public var rimTexture: Texture;
    public var rimTint: Float;
    public var roughness: Float;
    public var roughnessTexture: Texture;
    public var roughnessTextureChannel: Int;
    public var subsurfScatterEnabled: Bool;
    public var subsurfScatterStrength: Float;
    public var subsurfScatterTexture: Texture;
    public var transmission: Color;
    public var transmissionEnabled: Bool;
    public var transmissionTexture: Texture;
    public var uv1Offset: Vector3;
    public var uv1Scale: Vector3;
    public var uv1Triplanar: Bool;
    public var uv1TriplanarSharpness: Float;
    public var uv2Offset: Vector3;
    public var uv2Scale: Vector3;
    public var uv2Triplanar: Bool;
    public var uv2TriplanarSharpness: Float;
    public var vertexColorIsSrgb: Bool;
    public var vertexColorUseAsAlbedo: Bool;
    public function getFeature(feature: Int): Bool;
    public function getFlag(flag: Int): Bool;
    public function getTexture(param: Int): Texture;
    public function setFeature(feature: Int, enable: Bool): Void;
    public function setFlag(flag: Int, enable: Bool): Void;
    public function setTexture(param: Int, texture: Texture): Void;
    @:native("__new")
    public function new();
}
