package lucidKit.godot;

@:native("godot.Viewport")
extern class Viewport extends Node {
    public var arvr: Bool;
    public var audioListenerEnable2d: Bool;
    public var audioListenerEnable3d: Bool;
    public var canvasTransform: Transform2D;
    public var debanding: Bool;
    public var debugDraw: Int;
    public var disable3d: Bool;
    public var fxaa: Bool;
    public var globalCanvasTransform: Transform2D;
    public var guiDisableInput: Bool;
    public var guiSnapControlsToPixels: Bool;
    public var handleInputLocally: Bool;
    public var hdr: Bool;
    public var keep3dLinear: Bool;
    public var msaa: Int;
    public var ownWorld: Bool;
    public var physicsObjectPicking: Bool;
    public var renderDirectToScreen: Bool;
    public var renderTargetClearMode: Int;
    public var renderTargetUpdateMode: Int;
    public var renderTargetVFlip: Bool;
    public var shadowAtlasQuad0: Int;
    public var shadowAtlasQuad1: Int;
    public var shadowAtlasQuad2: Int;
    public var shadowAtlasQuad3: Int;
    public var shadowAtlasSize: Int;
    public var sharpenIntensity: Float;
    public var size: Vector2;
    public var sizeOverrideStretch: Bool;
    public var transparentBg: Bool;
    public var usage: Int;
    public var use32BpcDepth: Bool;
    public var world: World;
    public var world2d: World2D;
    public function findWorld(): World;
    public function findWorld2d(): World2D;
    public function getCamera(): Camera;
    public function getFinalTransform(): Transform2D;
    public function getModalStackTop(): Control;
    public function getMousePosition(): Vector2;
    public function getRenderInfo(info: Int): Int;
    public function getShadowAtlasQuadrantSubdiv(quadrant: Int): Int;
    public function getSizeOverride(): Vector2;
    public function getTexture(): ViewportTexture;
    public function getViewportRid(): RID;
    public function getVisibleRect(): Rect2;
    public function guiGetDragData(): Variant;
    public function guiHasModalStack(): Bool;
    public function guiIsDragSuccessful(): Bool;
    public function guiIsDragging(): Bool;
    public function input(localEvent: InputEvent): Void;
    public function isInputHandled(): Bool;
    public function isSizeOverrideEnabled(): Bool;
    public function setAttachToScreenRect(rect: Rect2): Void;
    public function setInputAsHandled(): Void;
    public function setShadowAtlasQuadrantSubdiv(quadrant: Int, subdiv: Int): Void;
    public function setSizeOverride(enable: Bool, size: GdVector2, margin: GdVector2): Void;
    public function unhandledInput(localEvent: InputEvent): Void;
    public function updateWorlds(): Void;
    public function warpMouse(toPosition: GdVector2): Void;
    @:native("__new")
    public function new();
}
